"use client";

import React, { useState } from "react";
import Link from "next/link";
import { 
  ShieldAlert, 
  FileCheck, 
  Search, 
  Cpu, 
  Layers, 
  Network, 
  ChevronRight, 
  Clock, 
  Award, 
  Database,
  ArrowRight,
  TrendingDown,
  Lock,
  Menu,
  X
} from "lucide-react";

export default function LandingPage() {
  const [showDemoModal, setShowDemoModal] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);

  // Statistics
  const statistics = [
    { title: "Avg. Loan Forgery Cost", value: "$4.2B", desc: "Annual bank losses due to altered documents", icon: TrendingDown, color: "text-red-400" },
    { title: "Tamper Detection Speed", value: "< 2.5s", desc: "Real-time ELA & layout forensic inspection", icon: Clock, color: "text-cyan-400" },
    { title: "Classification Accuracy", value: "99.4%", desc: "Advanced LayoutLMv3 & OCR extraction", icon: Cpu, color: "text-emerald-400" },
  ];

  // Features
  const features = [
    { title: "AI Forgery Detection", desc: "Scan structural patterns, copy-pasted signatures, and compression mismatches using neural vision networks.", icon: ShieldAlert },
    { title: "Tamper Heatmaps", desc: "Interactive canvas displaying localized anomalies with red, yellow, and green confidence overlays.", icon: Layers },
    { title: "OCR Intelligence", desc: "Auto-extract fields, align font structures, and detect kerning or size manipulation instantly.", icon: Search },
    { title: "Cross-Document Validation", desc: "Match applicant names, PAN card info, bank statements, and income taxes across files to flag mismatches.", icon: FileCheck },
    { title: "Metadata Analysis", desc: "Inspect creation dates, hidden GPS files, and identify Photoshop/GIMP editing software footprints.", icon: Database },
    { title: "Fraud Network Detection", desc: "Expose hidden loan syndicates, shared addresses, and co-applicant cycles using graph link metrics.", icon: Network },
  ];

  // FAQ list
  const faqs = [
    { q: "How does Error Level Analysis (ELA) identify document alterations?", a: "ELA compresses the uploaded document at a fixed ratio and measures pixel difference. Digitally edited areas stand out with distinct glow ratios because their compression signatures deviate from the background scan." },
    { q: "Is DocuShield AI compliant with Reserve Bank of India guidelines?", a: "Yes, our architecture integrates the RBI Section 12.A & 19.F banking rules, maintaining secure local ledger hosting, role-based encryption access, and audit log tracking." },
    { q: "What types of loan document file extensions are supported?", a: "We support PDFs, high-resolution PNGs, JPG scans, and TIFF images commonly generated by corporate scanners." },
  ];

  return (
    <div className="min-h-screen bg-slate-950 font-sans relative overflow-x-hidden">
      
      {/* Cyber Grid Background */}
      <div className="absolute inset-0 cyber-grid opacity-30 pointer-events-none z-0" />
      <div className="absolute top-[-10%] left-[-10%] w-[50%] h-[50%] bg-indigo-900/10 rounded-full blur-[120px] pointer-events-none z-0" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[50%] h-[50%] bg-cyan-900/10 rounded-full blur-[120px] pointer-events-none z-0" />

      {/* FULLSCREEN MOBILE NAVIGATION OVERLAY */}
      {menuOpen && (
        <div className="fixed inset-0 z-[100] bg-slate-950/98 backdrop-blur-2xl flex flex-col justify-between p-6 md:hidden overflow-y-auto">
          <div>
            {/* Mobile Header Bar */}
            <div className="flex items-center justify-between pb-5 border-b border-slate-800">
              <div className="flex items-center space-x-3">
                <div className="p-2 bg-cyan-950 border border-accent/30 rounded-lg shadow-cyber shrink-0">
                  <ShieldAlert className="w-5 h-5 text-accent animate-pulse" />
                </div>
                <div>
                  <span className="text-lg font-bold tracking-wider font-sans text-white">
                    DOCUSHIELD <span className="text-accent text-sm font-light">AI</span>
                  </span>
                  <p className="text-[8px] text-slate-400 tracking-widest uppercase">Underwriting Guard</p>
                </div>
              </div>
              <button 
                onClick={() => setMenuOpen(false)}
                aria-label="Close navigation menu"
                className="p-2 rounded-lg border border-slate-800 bg-slate-900 text-slate-400 hover:text-white"
              >
                <X className="w-6 h-6 text-accent" />
              </button>
            </div>

            {/* Navigation Links */}
            <div className="mt-8 flex flex-col space-y-2">
              <p className="text-[10px] font-mono uppercase tracking-widest text-slate-500 pb-2 border-b border-slate-900">Platform Navigation</p>
              <a 
                href="#problem" 
                onClick={() => setMenuOpen(false)} 
                className="text-base font-bold text-slate-200 hover:text-accent py-3 transition-colors flex items-center justify-between border-b border-slate-900"
              >
                <span>Risk Index</span>
                <ChevronRight className="w-4 h-4 text-slate-600" />
              </a>
              <a 
                href="#features" 
                onClick={() => setMenuOpen(false)} 
                className="text-base font-bold text-slate-200 hover:text-accent py-3 transition-colors flex items-center justify-between border-b border-slate-900"
              >
                <span>Core Intelligence</span>
                <ChevronRight className="w-4 h-4 text-slate-600" />
              </a>
              <a 
                href="#workflow" 
                onClick={() => setMenuOpen(false)} 
                className="text-base font-bold text-slate-200 hover:text-accent py-3 transition-colors flex items-center justify-between border-b border-slate-900"
              >
                <span>Workflow</span>
                <ChevronRight className="w-4 h-4 text-slate-600" />
              </a>
              <a 
                href="#security" 
                onClick={() => setMenuOpen(false)} 
                className="text-base font-bold text-slate-200 hover:text-accent py-3 transition-colors flex items-center justify-between border-b border-slate-900"
              >
                <span>Compliance</span>
                <ChevronRight className="w-4 h-4 text-slate-600" />
              </a>
              <a 
                href="#faq" 
                onClick={() => setMenuOpen(false)} 
                className="text-base font-bold text-slate-200 hover:text-accent py-3 transition-colors flex items-center justify-between"
              >
                <span>Security FAQ</span>
                <ChevronRight className="w-4 h-4 text-slate-600" />
              </a>
            </div>
          </div>

          {/* Action CTAs */}
          <div className="pt-6 border-t border-slate-800/80 flex flex-col space-y-3">
            <button 
              onClick={() => { setMenuOpen(false); setShowDemoModal(true); }}
              className="w-full py-3.5 rounded-xl border border-slate-700 bg-slate-900 text-sm font-semibold text-slate-200 hover:bg-slate-800 text-center transition-all"
            >
              Request Live Demo
            </button>
            <Link 
              href="/login" 
              onClick={() => setMenuOpen(false)} 
              className="w-full py-4 bg-accent hover:bg-cyan-400 text-center text-slate-950 font-bold rounded-xl text-sm shadow-cyber transition-all"
            >
              Start Analysis Session
            </Link>
          </div>
        </div>
      )}

      {/* HEADER / TOP NAVBAR */}
      <header className="sticky top-0 z-40 border-b border-slate-800/80 bg-slate-950/95 backdrop-blur-xl">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 h-20 flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="p-2 sm:p-2.5 bg-cyan-950 border border-accent/30 rounded-lg shadow-cyber shrink-0">
              <ShieldAlert className="w-5 h-5 sm:w-6 sm:h-6 text-accent animate-pulse" />
            </div>
            <div>
              <span className="text-lg sm:text-xl font-bold tracking-wider font-sans text-white">
                DOCUSHIELD <span className="text-accent text-sm font-light">AI</span>
              </span>
              <p className="text-[8px] sm:text-[9px] text-slate-400 tracking-widest uppercase">Underwriting Guard</p>
            </div>
          </div>

          {/* Desktop Nav Links */}
          <nav className="hidden md:flex items-center space-x-8 text-sm font-medium text-slate-300">
            <a href="#problem" className="hover:text-accent transition-colors">Risk Index</a>
            <a href="#features" className="hover:text-accent transition-colors">Core Intelligence</a>
            <a href="#workflow" className="hover:text-accent transition-colors">Workflow</a>
            <a href="#security" className="hover:text-accent transition-colors">Compliance</a>
            <a href="#faq" className="hover:text-accent transition-colors">Security FAQ</a>
          </nav>

          <div className="hidden md:flex items-center space-x-4">
            <button 
              onClick={() => setShowDemoModal(true)}
              className="px-5 py-2.5 rounded-lg border border-slate-700 text-sm font-medium hover:bg-slate-800 hover:border-slate-600 transition-all"
            >
              Request Demo
            </button>
            <Link 
              href="/login"
              className="px-5 py-2.5 bg-accent hover:bg-cyan-400 text-slate-950 rounded-lg text-sm font-semibold shadow-cyber hover:shadow-cyberGlow transition-all duration-300"
            >
              Start Analysis
            </Link>
          </div>

          {/* Mobile Menu Button */}
          <button 
            onClick={() => setMenuOpen(true)} 
            aria-label="Open Navigation Menu"
            className="md:hidden p-2 rounded-lg border border-slate-800 bg-slate-900/80 text-white hover:text-accent transition-colors"
          >
            <Menu className="w-6 h-6" />
          </button>
        </div>
      </header>

      {/* HERO SECTION */}
      <section className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 pt-12 sm:pt-16 pb-16 sm:pb-24 text-center">
        <div className="inline-flex items-center space-x-2 px-3.5 py-1.5 rounded-full bg-cyan-950/60 border border-accent/20 text-[11px] sm:text-xs text-accent mb-6 sm:mb-8 shadow-cyber max-w-full">
          <Award className="w-3.5 h-3.5 shrink-0 animate-spin" style={{ animationDuration: '6s' }} />
          <span className="font-semibold tracking-wider uppercase font-sans truncate">Next-Gen Underwriting Security Platform</span>
        </div>

        <h1 className="text-3xl sm:text-5xl md:text-6xl font-extrabold tracking-tight text-white mb-6 font-sans max-w-4xl mx-auto leading-tight sm:leading-tight md:leading-[1.1] px-2">
          AI-Powered Document <br className="hidden sm:block" />
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-accent via-indigo-300 to-white glow-cyan">
            Fraud & Forgery Detection
          </span>
        </h1>

        <p className="text-sm sm:text-lg md:text-xl text-slate-400 mb-8 sm:mb-10 max-w-2xl mx-auto font-sans font-light leading-relaxed px-2">
          Detect document tampering, AI-generated forgery, metadata anomalies, and loan underwriting fraud in real time before it hits your ledger.
        </p>

        <div className="flex flex-col sm:flex-row items-center justify-center gap-3 sm:gap-4 w-full max-w-md sm:max-w-none mx-auto">
          <Link 
            href="/login"
            className="w-full sm:w-auto px-8 py-4 bg-accent hover:bg-cyan-400 text-slate-950 rounded-xl text-base font-bold shadow-cyber hover:shadow-cyberGlow flex items-center justify-center space-x-2.5 transition-all duration-300 group"
          >
            <span>Start Analysis Session</span>
            <ChevronRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
          </Link>
          <button 
            onClick={() => setShowDemoModal(true)}
            className="w-full sm:w-auto px-8 py-4 bg-slate-900 border border-slate-700 hover:border-slate-500 text-white rounded-xl text-base font-semibold transition-all"
          >
            Schedule Live Underwrite Demo
          </button>
        </div>

        {/* Dynamic App Preview Mockup */}
        <div className="mt-14 sm:mt-20 max-w-5xl mx-auto relative group">
          <div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-transparent to-transparent z-10" />
          <div className="absolute -inset-1 rounded-2xl bg-gradient-to-r from-accent/20 to-indigo-500/20 blur-xl opacity-75 group-hover:opacity-100 transition duration-1000 group-hover:duration-200" />
          
          <div className="relative border border-slate-800 rounded-2xl bg-slate-900/90 shadow-2xl overflow-hidden glass-panel">
            <div className="h-11 border-b border-slate-800 bg-slate-950/80 px-4 sm:px-6 flex items-center space-x-2">
              <span className="w-3 h-3 rounded-full bg-red-500/80" />
              <span className="w-3 h-3 rounded-full bg-yellow-500/80" />
              <span className="w-3 h-3 rounded-full bg-emerald-500/80" />
              <span className="text-[11px] sm:text-xs text-slate-500 ml-2 sm:ml-4 font-mono truncate">docushield.security.canarabank.in/scanner</span>
            </div>
            
            <div className="p-4 sm:p-8 grid grid-cols-1 md:grid-cols-2 gap-6 sm:gap-8 text-left">
              {/* Fake visual ELA panel */}
              <div className="border border-red-500/30 bg-slate-950 p-4 sm:p-6 rounded-xl relative overflow-hidden scanline min-h-[220px] sm:min-h-[250px]">
                <span className="absolute top-3 right-3 sm:top-4 sm:right-4 bg-red-500/10 border border-red-500/40 text-red-400 text-[10px] sm:text-xs px-2.5 py-1 rounded font-mono uppercase tracking-widest">
                  CRITICAL FRAUD
                </span>
                <p className="text-[9px] sm:text-[10px] text-slate-500 font-mono tracking-wider mb-2">FORENSIC ELA HEATMAP VIEW</p>
                <div className="h-32 sm:h-40 flex flex-col justify-center items-center border border-dashed border-slate-800 rounded-lg relative bg-[radial-gradient(#1e293b_1px,transparent_1px)] bg-[size:16px_16px]">
                  <ShieldAlert className="w-10 h-10 sm:w-12 sm:h-12 text-red-500 animate-pulse mb-2 sm:mb-3" />
                  <p className="text-xs sm:text-sm font-semibold text-slate-300 text-center px-2">Monthly Income Box Tampered</p>
                  <p className="text-[10px] sm:text-[11px] text-slate-500 font-mono text-center">Discrepancy Multiplier: 25.0x</p>
                </div>
              </div>
              
              {/* Fake visual stats */}
              <div className="flex flex-col justify-between space-y-6 md:space-y-0">
                <div>
                  <h3 className="text-lg sm:text-xl font-bold text-white mb-1 sm:mb-2">Loan Verification Forensic Scan</h3>
                  <p className="text-xs sm:text-sm text-slate-400 mb-4 sm:mb-6 truncate">Sunita_Kumar_SalarySlip_Tampered.png</p>
                  
                  <div className="space-y-3 sm:space-y-4 text-xs sm:text-sm">
                    <div className="flex justify-between border-b border-slate-800 pb-2">
                      <span className="text-slate-500">Tamper Risk Rating</span>
                      <span className="text-red-400 font-bold uppercase glow-red">92.6% (CRITICAL)</span>
                    </div>
                    <div className="flex justify-between border-b border-slate-800 pb-2">
                      <span className="text-slate-500">EXIF Software Footprint</span>
                      <span className="text-yellow-400 font-medium">Adobe Photoshop 2025</span>
                    </div>
                    <div className="flex justify-between border-b border-slate-800 pb-2">
                      <span className="text-slate-500">Font Integrity Spacing</span>
                      <span className="text-red-400 font-medium">Alert: Mismatch Patched Box</span>
                    </div>
                  </div>
                </div>
                
                <Link 
                  href="/login"
                  className="w-full text-center py-3 bg-slate-800 hover:bg-slate-700 text-accent font-semibold rounded-lg text-xs sm:text-sm border border-accent/20 transition-all"
                >
                  Inspect Case Record
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* STATISTICS CARDS */}
      <section id="problem" className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 py-10 sm:py-12 border-t border-slate-900 bg-slate-950/40">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {statistics.map((stat, i) => {
            const Icon = stat.icon;
            return (
              <div key={i} className="p-8 rounded-2xl border border-slate-800 bg-slate-900/40 backdrop-blur flex items-start space-x-6">
                <div className={`p-4 bg-slate-950 rounded-xl border border-slate-800`}>
                  <Icon className={`w-8 h-8 ${stat.color}`} />
                </div>
                <div>
                  <p className="text-3xl font-extrabold text-white mb-1 font-sans">{stat.value}</p>
                  <p className="text-sm font-semibold text-slate-300 mb-1">{stat.title}</p>
                  <p className="text-xs text-slate-500 leading-relaxed">{stat.desc}</p>
                </div>
              </div>
            );
          })}
        </div>
      </section>

      {/* PROBLEM STATEMENT */}
      <section className="relative z-10 max-w-7xl mx-auto px-6 py-20">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h2 className="text-3xl font-bold text-white mb-4">The Underwriting Tampering Challenge</h2>
          <p className="text-slate-400 text-base leading-relaxed">
            Standard Optical Character Recognition (OCR) systems extract text but fail to identify pixel manipulation, metadata changes, font differences, and duplicate property syndicates, leaving banks vulnerable to forged loan portfolios.
          </p>
        </div>
      </section>

      {/* FEATURE CARDS */}
      <section id="features" className="relative z-10 max-w-7xl mx-auto px-6 py-12">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h2 className="text-3xl font-extrabold text-white mb-4">DocuShield Security Features</h2>
          <p className="text-slate-400">Our machine learning models perform deep pixel-level inspections.</p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {features.map((feat, i) => {
            const Icon = feat.icon;
            return (
              <div key={i} className="p-8 rounded-2xl border border-slate-900 bg-slate-900/20 backdrop-blur hover:border-accent/30 transition-all duration-300 group">
                <div className="w-12 h-12 bg-cyan-950/50 border border-accent/20 rounded-xl flex items-center justify-center mb-6 shadow-cyber">
                  <Icon className="w-6 h-6 text-accent group-hover:scale-110 transition-transform" />
                </div>
                <h3 className="text-lg font-bold text-slate-200 mb-3">{feat.title}</h3>
                <p className="text-sm text-slate-500 leading-relaxed">{feat.desc}</p>
              </div>
            );
          })}
        </div>
      </section>

      {/* WORKFLOW PIPELINE SECTION */}
      <section id="workflow" className="relative z-10 max-w-7xl mx-auto px-6 py-24 border-t border-slate-900 bg-slate-950/40">
        <div className="text-center max-w-3xl mx-auto mb-20">
          <h2 className="text-3xl font-extrabold text-white mb-4">Underwriting Analysis Workflow</h2>
          <p className="text-slate-400">Multi-stage document verification pipeline executed in seconds.</p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-5 gap-8 text-center relative">
          
          {/* Timeline steps */}
          {[
            { step: "01", name: "Upload Document", desc: "PDF, PNG, JPG, or TIFF files mapped to case." },
            { step: "02", name: "OCR Extraction", desc: "Digitize text content and mapping blocks." },
            { step: "03", name: "Forensic Analysis", desc: "Run Error Level Analysis and metadata inspection." },
            { step: "04", name: "Fraud Scoring", desc: "Flag font variance and copy-pasted signatures." },
            { step: "05", name: "Underwriter Review", desc: "Verify alerts, graph ring ties, and lock decision." }
          ].map((item, idx) => (
            <div key={idx} className="relative flex flex-col items-center group">
              <div className="w-14 h-14 bg-slate-900 border border-slate-800 rounded-full flex items-center justify-center mb-6 text-accent font-bold font-mono text-lg shadow-cyber relative z-10 group-hover:border-accent group-hover:bg-cyan-950 transition-all duration-300">
                {item.step}
              </div>
              <h4 className="text-base font-bold text-white mb-2">{item.name}</h4>
              <p className="text-xs text-slate-500 leading-relaxed px-4">{item.desc}</p>
              
              {/* Connector line for large screens */}
              {idx < 4 && (
                <div className="hidden md:block absolute top-7 left-[calc(50%+28px)] w-[calc(100%-56px)] h-0.5 bg-gradient-to-r from-cyan-950 via-accent/30 to-slate-900" />
              )}
            </div>
          ))}
        </div>
      </section>

      {/* RBI COMPLIANCE & SECURITY SHOWCASE */}
      <section id="security" className="relative z-10 max-w-7xl mx-auto px-6 py-20 border-t border-slate-900">
        <div className="p-10 md:p-14 bg-slate-900/60 rounded-3xl border border-slate-800 relative overflow-hidden flex flex-col md:flex-row items-center justify-between gap-10">
          <div className="absolute inset-0 cyber-grid opacity-10 pointer-events-none" />
          
          <div className="max-w-2xl relative z-10">
            <div className="inline-flex items-center space-x-2 text-xs text-emerald-400 bg-emerald-950/40 border border-emerald-500/20 px-3 py-1 rounded-full mb-6 font-semibold uppercase font-sans">
              <Lock className="w-3.5 h-3.5 animate-pulse" />
              <span>Canara Bank RBI Audited Platform</span>
            </div>
            
            <h2 className="text-3xl md:text-4xl font-extrabold text-white mb-4">
              RBI Compliant Banking Security
            </h2>
            <p className="text-sm text-slate-400 leading-relaxed mb-6">
              Our framework includes full support for the Reserve Bank of India (RBI) Cyber Security Guidelines. This includes complete audit trails, multi-factor JWT tokens, and strict role based RBAC authorization for Admin, Underwriters, and Auditors.
            </p>
            
            <div className="grid grid-cols-2 gap-4">
              <div className="flex items-center space-x-2 text-xs text-slate-300">
                <FileCheck className="w-4 h-4 text-emerald-400" />
                <span>Audited Ledger Logs</span>
              </div>
              <div className="flex items-center space-x-2 text-xs text-slate-300">
                <FileCheck className="w-4 h-4 text-emerald-400" />
                <span>AES-256 Storage Shields</span>
              </div>
            </div>
          </div>
          
          <div className="relative z-10 shrink-0">
            <div className="w-48 h-48 bg-slate-950 border border-slate-800 rounded-full flex flex-col items-center justify-center shadow-cyber relative">
              <div className="absolute inset-1 rounded-full border border-accent/20 animate-spin" style={{ animationDuration: '10s' }} />
              <ShieldAlert className="w-14 h-14 text-accent mb-2" />
              <span className="text-sm font-extrabold text-white">COMPLIANT</span>
              <span className="text-[10px] text-slate-500 tracking-wider">RBI COMPLIANCE</span>
            </div>
          </div>
        </div>
      </section>

      {/* FAQS SECTION */}
      <section id="faq" className="relative z-10 max-w-4xl mx-auto px-6 py-20 border-t border-slate-900">
        <h2 className="text-3xl font-extrabold text-white text-center mb-12">Frequently Asked Questions</h2>
        <div className="space-y-6">
          {faqs.map((faq, i) => (
            <div key={i} className="p-6 rounded-xl border border-slate-900 bg-slate-900/10">
              <h4 className="text-base font-bold text-white mb-2">{faq.q}</h4>
              <p className="text-sm text-slate-400 leading-relaxed">{faq.a}</p>
            </div>
          ))}
        </div>
      </section>

      {/* FOOTER */}
      <footer className="relative z-10 border-t border-slate-900 bg-slate-950 px-6 py-12">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-6 text-sm text-slate-500">
          <div className="flex items-center space-x-3">
            <ShieldAlert className="w-5 h-5 text-accent" />
            <span className="font-bold text-slate-300">DocuShield AI</span>
          </div>
          
          <p>© 2026 DocuShield AI. All rights reserved. Designed for Canara Bank security operations.</p>
          
          <div className="flex items-center space-x-6">
            <a href="#" className="hover:text-accent">Terms</a>
            <a href="#" className="hover:text-accent">Privacy</a>
            <a href="#" className="hover:text-accent">RBI Ledger Docs</a>
          </div>
        </div>
      </footer>

      {/* DEMO MODAL POPUP */}
      {showDemoModal && (
        <div className="fixed inset-0 bg-slate-950/80 backdrop-blur-md flex items-center justify-center p-4 z-50 animate-fade-in">
          <div className="w-full max-w-md bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl overflow-hidden glass-panel">
            <div className="p-6 border-b border-slate-800 flex justify-between items-center">
              <h3 className="text-lg font-bold text-white">Request Underwriter Trial</h3>
              <button onClick={() => setShowDemoModal(false)} className="text-slate-400 hover:text-white">
                <X className="w-5 h-5" />
              </button>
            </div>
            
            <form onSubmit={(e) => { e.preventDefault(); setShowDemoModal(false); alert("Request received. A fintech representative will contact your bank within 2 hours."); }} className="p-6 space-y-4">
              <div>
                <label className="block text-xs font-semibold text-slate-400 uppercase mb-2">Corporate Email</label>
                <input required type="email" placeholder="name@canarabank.in" className="w-full bg-slate-950 border border-slate-800 rounded-lg px-4 py-3 text-sm text-white focus:border-accent outline-none" />
              </div>
              <div>
                <label className="block text-xs font-semibold text-slate-400 uppercase mb-2">Your Department</label>
                <select className="w-full bg-slate-950 border border-slate-800 rounded-lg px-4 py-3 text-sm text-white focus:border-accent outline-none">
                  <option>Home Loan Underwriting</option>
                  <option>Risk Management Division</option>
                  <option>Information Security & Auditor</option>
                </select>
              </div>
              <button type="submit" className="w-full py-3 bg-accent text-slate-950 font-bold rounded-lg text-sm transition-all hover:bg-cyan-400 shadow-cyber">
                Submit Access Request
              </button>
            </form>
          </div>
        </div>
      )}

    </div>
  );
}
